### ISSUE TITLE
Expected image input for the bash scripts?

### ISSUE THREAD

**Issue by R4to0** [blind-coder/deepzoom-utils#1]
Hello,

Just came after successfully running the mapmap tool you also made to this, but reading the bash scripts I see it expects a different image input than what mapmap actually generates. We have images for each cells and levels but the bash scripts uses a specific pattern name for the files. Are the any pre-processing requirement before using these or am I completely blind and missed something that is in the scripts already (heh)?

att.

**Comment by blind-coder** [comment]
Ooof, right. There is an intermediate step, which I think I never documented or uploaded. And it's not nice, either. Basically, you need to stitch the files together to square images. I'll do that some time this week.

**Comment by blind-coder** [comment]
I have created https://github.com/blind-coder/pz-to-deepzoom for an easier flow. It's not perfect yet, needs more tweaking, but if you already came this far, it should help you :)

**Comment by R4to0** [comment]
Thanks a lot for the hard work, you're amazing! Hope that didn't consumed much your time as its been a long time since you've touched the repos 😅. I'll try those.

**Comment by blind-coder** [comment]
Let's just say it was way past time I made it. Let's continue discussion over there.
